management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env, httptrace
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Champions League Game API
    description: Java backend for guessing football players
    version: 1.0.0